filepath: ""
helmfiles:
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/kuberhealthy/helmfile.yaml
- path: helmfiles/nginx/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
repositories:
- name: kuberhealthy
  url: https://comcast.github.io/kuberhealthy/helm-repos
releases:
- chart: kuberhealthy/kuberhealthy
  version: "64"
  name: kuberhealthy
  namespace: kuberhealthy
  values:
  - versionStream/charts/kuberhealthy/kuberhealthy/values.yaml.gotmpl
templates: {}
renderedvalues: {}
