jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    gitKind: github
    gitName: github
    gitServer: https://github.com
    namespace: jx
  ingress:
    domain: ""
    customHosts:
       hook: "12cc587de2ef.ngrok.io"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: false
      url: ""
    reports:
      enabled: false
      url: ""
    repository:
      enabled: false
      url: ""
  vault: {}
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: ""
    url: ""
  webhook: prow
